import { useState } from 'react'

const ISO_MAP: Record<string, string> = {
  'México':'mx',
  'Equador':'ec',
  'Canadá':'ca',
  'África do Sul':'za',
  'Coreia do Sul':'kr',
  'Tchéquia':'cz',
  'Bosnia & Herzegovina':'ba',
  'Bósnia e Herzegovina':'ba',
  'Estados Unidos':'us',
  'Paraguai':'py',
  'Qatar':'qa',
  'Catar':'qa',
  'Suíça':'ch',
  'Brasil':'br',
  'Marrocos':'ma',
  'Haiti':'ht',
  'Escócia':'gb-sct',
  'Alemanha':'de',
  'Uruguai':'uy',
  'Espanha':'es',
  'Bélgica':'be',
  'França':'fr',
  'Argentina':'ar',
  'Portugal':'pt',
  'Inglaterra':'gb-eng',
  'Países Baixos':'nl',
  'Itália':'it',
  'Croácia':'hr',
  'Sérvia':'rs',
  'Dinamarca':'dk',
  'Áustria':'at',
  'Turquia':'tr',
  'Geórgia':'ge',
  'Japão':'jp',
  'Austrália':'au',
  'Nigéria':'ng',
  'Camarões':'cm',
  'Arábia Saudita':'sa',
  'Irã':'ir',
  'Iraque':'iq',
  'Israel':'il',
  'Jamaica':'jm',
  'Peru':'pe',
  'Chile':'cl',
  'Colômbia':'co',
  'Venezuela':'ve',
  'Bolívia':'bo',
  'Senegal':'sn',
  'Gana':'gh',
  'Noruega':'no',
  'Suécia':'se',
  'Polônia':'pl',
  'Grécia':'gr',
  'Ucrânia':'ua',
  'Hungria':'hu',
  'Eslováquia':'sk',
  'Eslovênia':'si',
  'Romênia':'ro',
  'Cazaquistão':'kz',
  'Albânia':'al',
  'Moçambique':'mz',
  'RD Congo':'cd',
  'Nova Zelândia':'nz',
  'Panamá':'pa',
  'Honduras':'hn',
  'Costa Rica':'cr',
  'El Salvador':'sv',
  'Tunísia':'tn',
  'Argélia':'dz',
  'Egito':'eg',
  'Finlândia':'fi',
  'Islândia':'is',
  'Kosovo':'xk',
  'Luxemburgo':'lu',
  'Uzbequistão':'uz',
  'Uzbekistan':'uz',
  'Curaçao':'cw',
  'Cape Verde':'cv',
  'Jordan':'jo',
  'Costa do Marfim':'ci',
  'País de Gales':'gb-wls',
  'Tchequia':'cz',
  'Albania':'al',
  'Mexico':'mx',
  'Ecuador':'ec',
  'Canada':'ca',
  'South Africa':'za',
  'Korea Republic':'kr',
  'South Korea':'kr',
  'Czech Republic':'cz',
  'Czechia':'cz',
  'Bosnia and Herzegovina':'ba',
  'Bosnia-Herzegovina':'ba',
  'United States':'us',
  'USA':'us',
  'Switzerland':'ch',
  'Brazil':'br',
  'Morocco':'ma',
  'Germany':'de',
  'Uruguay':'uy',
  'Spain':'es',
  'Belgium':'be',
  'France':'fr',
  'Netherlands':'nl',
  'Italy':'it',
  'Croatia':'hr',
  'Serbia':'rs',
  'Denmark':'dk',
  'Austria':'at',
  'Turkey':'tr',
  'Turkiye':'tr',
  'Georgia':'ge',
  'Japan':'jp',
  'Australia':'au',
  'Nigeria':'ng',
  'Cameroon':'cm',
  'Saudi Arabia':'sa',
  'Iran':'ir',
  'Iraq':'iq',
  'England':'gb-eng',
  'Wales':'gb-wls',
  'Scotland':'gb-sct',
  'Colombia':'co',
  'Bolivia':'bo',
  'Ghana':'gh',
  'Norway':'no',
  'Sweden':'se',
  'Poland':'pl',
  'Greece':'gr',
  'Ukraine':'ua',
  'Hungary':'hu',
  'Slovakia':'sk',
  'Slovenia':'si',
  'Romania':'ro',
  'Kazakhstan':'kz',
  'Mozambique':'mz',
  'DR Congo':'cd',
  'New Zealand':'nz',
  'Panama':'pa',
  'Tunisia':'tn',
  'Algeria':'dz',
  'Egypt':'eg',
  'Finland':'fi',
  'Iceland':'is',
  'Paraguay':'py',
  'Ivory Coast':'ci',
  'Cote d'Ivoire':'ci',
  'Trinidad and Tobago':'tt',
  'Indonesia':'id',
  'Curacao':'cw',
}

const EMOJI: Record<string, string> = {
  'mx':'🇲🇽',
  'ec':'🇪🇨',
  'ca':'🇨🇦',
  'za':'🇿🇦',
  'kr':'🇰🇷',
  'cz':'🇨🇿',
  'ba':'🇧🇦',
  'us':'🇺🇸',
  'py':'🇵🇾',
  'qa':'🇶🇦',
  'ch':'🇨🇭',
  'br':'🇧🇷',
  'ma':'🇲🇦',
  'ht':'🇭🇹',
  'gb-sct':'🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'de':'🇩🇪',
  'uy':'🇺🇾',
  'es':'🇪🇸',
  'be':'🇧🇪',
  'fr':'🇫🇷',
  'ar':'🇦🇷',
  'pt':'🇵🇹',
  'gb-eng':'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'nl':'🇳🇱',
  'it':'🇮🇹',
  'hr':'🇭🇷',
  'rs':'🇷🇸',
  'dk':'🇩🇰',
  'at':'🇦🇹',
  'tr':'🇹🇷',
  'ge':'🇬🇪',
  'jp':'🇯🇵',
  'au':'🇦🇺',
  'ng':'🇳🇬',
  'cm':'🇨🇲',
  'sa':'🇸🇦',
  'ir':'🇮🇷',
  'iq':'🇮🇶',
  'il':'🇮🇱',
  'jm':'🇯🇲',
  'pe':'🇵🇪',
  'cl':'🇨🇱',
  'co':'🇨🇴',
  've':'🇻🇪',
  'bo':'🇧🇴',
  'sn':'🇸🇳',
  'gh':'🇬🇭',
  'no':'🇳🇴',
  'se':'🇸🇪',
  'pl':'🇵🇱',
  'gr':'🇬🇷',
  'ua':'🇺🇦',
  'hu':'🇭🇺',
  'sk':'🇸🇰',
  'si':'🇸🇮',
  'ro':'🇷🇴',
  'kz':'🇰🇿',
  'al':'🇦🇱',
  'mz':'🇲🇿',
  'cd':'🇨🇩',
  'nz':'🇳🇿',
  'pa':'🇵🇦',
  'hn':'🇭🇳',
  'cr':'🇨🇷',
  'sv':'🇸🇻',
  'tn':'🇹🇳',
  'dz':'🇩🇿',
  'eg':'🇪🇬',
  'fi':'🇫🇮',
  'is':'🇮🇸',
  'xk':'🇽🇰',
  'lu':'🇱🇺',
  'uz':'🇺🇿',
  'cw':'🇨🇼',
  'cv':'🇨🇻',
  'jo':'🇯🇴',
  'ci':'🇨🇮',
  'tt':'🇹🇹',
  'id':'🇮🇩',
  'gb-wls':'🏴󠁧󠁢󠁷󠁬󠁳󠁿',
}

type Props = { team: string; dbFlag?: string; size?: number; className?: string }

export default function FlagImg({ team, size = 40, className = '' }: Props) {
  const lower = team.toLowerCase()
  let iso = ISO_MAP[team]
  if (!iso) {
    const e = Object.entries(ISO_MAP).find(([k]) => k.toLowerCase() === lower)
    if (e) iso = e[1]
  }
  if (!iso) {
    const e = Object.entries(ISO_MAP).find(([k]) =>
      lower.includes(k.toLowerCase()) || k.toLowerCase().includes(lower)
    )
    if (e) iso = e[1]
  }
  const emoji = iso ? (EMOJI[iso] || '🏳️') : '🏳️'
  return (
    <span style={{ fontSize: size, lineHeight: 1 }}
      className={`leading-none select-none block text-center ${className}`}
      role="img" aria-label={team}>{emoji}</span>
  )
}
